export const algerianStates: { name: string; label: string; number: string }[] =
  [
    { name: "adrar", label: "Adrar", number: "01" },
    { name: "chlef", label: "Chlef", number: "02" },
    { name: "laghouat", label: "Laghouat", number: "03" },
    { name: "oum el bouaghi", label: "Oum El Bouaghi", number: "04" },
    { name: "batna", label: "Batna", number: "05" },
    { name: "béjaïa", label: "Béjaïa", number: "06" },
    { name: "biskra", label: "Biskra", number: "07" },
    { name: "béchar", label: "Béchar", number: "08" },
    { name: "blida", label: "Blida", number: "09" },
    { name: "bouira", label: "Bouira", number: "10" },
    { name: "tamanrasset", label: "Tamanrasset", number: "11" },
    { name: "tébessa", label: "Tébessa", number: "12" },
    { name: "tlemcen", label: "Tlemcen", number: "13" },
    { name: "tiaret", label: "Tiaret", number: "14" },
    { name: "tizi ouzou", label: "Tizi Ouzou", number: "15" },
    { name: "algiers", label: "Algiers", number: "16" },
    { name: "djelfa", label: "Djelfa", number: "17" },
    { name: "jijel", label: "Jijel", number: "18" },
    { name: "sétif", label: "Sétif", number: "19" },
    { name: "saïda", label: "Saïda", number: "20" },
    { name: "skikda", label: "Skikda", number: "21" },
    { name: "sidi bel abbès", label: "Sidi Bel Abbès", number: "22" },
    { name: "annaba", label: "Annaba", number: "23" },
    { name: "guelma", label: "Guelma", number: "24" },
    { name: "constantine", label: "Constantine", number: "25" },
    { name: "médea", label: "Médéa", number: "26" },
    { name: "mostaganem", label: "Mostaganem", number: "27" },
    { name: "m'sila", label: "M'Sila", number: "28" },
    { name: "mascara", label: "Mascara", number: "29" },
    { name: "ouargla", label: "Ouargla", number: "30" },
    { name: "oran", label: "Oran", number: "31" },
    { name: "el bayadh", label: "El Bayadh", number: "32" },
    { name: "illizi", label: "Illizi", number: "33" },
    { name: "bordj bou arréridj", label: "Bordj Bou Arréridj", number: "34" },
    { name: "boumerdès", label: "Boumerdès", number: "35" },
    { name: "el tarf", label: "El Tarf", number: "36" },
    { name: "tindouf", label: "Tindouf", number: "37" },
    { name: "tissemsilt", label: "Tissemsilt", number: "38" },
    { name: "el oued", label: "El Oued", number: "39" },
    { name: "khenchela", label: "Khenchela", number: "40" },
    { name: "souk ahras", label: "Souk Ahras", number: "41" },
    { name: "tipaza", label: "Tipaza", number: "42" },
    { name: "mila", label: "Mila", number: "43" },
    { name: "aïn defla", label: "Aïn Defla", number: "44" },
    { name: "naâma", label: "Naâma", number: "45" },
    { name: "aïn témouchent", label: "Aïn Témouchent", number: "46" },
    { name: "ghardaïa", label: "Ghardaïa", number: "47" },
    { name: "relizane", label: "Relizane", number: "48" },
    { name: "timimoun", label: "Timimoun", number: "49" },
    { name: "bordj badji mokhtar", label: "Bordj Badji Mokhtar", number: "50" },
    { name: "ouled djellal", label: "Ouled Djellal", number: "51" },
    { name: "béni abbès", label: "Béni Abbès", number: "52" },
    { name: "in salah", label: "In Salah", number: "53" },
    { name: "in guezzam", label: "In Guezzam", number: "54" },
    { name: "touggourt", label: "Touggourt", number: "55" },
    { name: "djanet", label: "Djanet", number: "56" },
    { name: "el m'ghair", label: "El M'Ghair", number: "57" },
    { name: "el menia", label: "El Menia", number: "58" },
  ];
